### ISSUE TITLE
MyRobot missing

### ISSUE THREAD

**Issue by knoetherich** [Mahmoud-Elbarrawy/Bachelor_Thesis_Project#1]
Hi, i would love to try your work! But there is a function missing...
![errorrobot](https://user-images.githubusercontent.com/79964119/204097461-b41fc63e-59bf-4890-a868-7f2dea4e8e88.png)

Can you please upload it?

**Comment by Mahmoud-Elbarrawy** [comment]
Hi, This project was in late 2018 back then I was not using GitHub. However, I just uploaded the file, check it. And good luck with your project.
